config/routes.rb
Sc2tvZaklady::Application.routes.draw do

  resources :suggestions

  devise_for :admins
  devise_for :users
  
  resources :posts do
    resources :comments
  end
  
  resources :duels do
    member do
      get :result
      put :make_result
    end
    resources :bets
  end

  resources :users do
    resources :bets
  end

  resources :suggestions

  match ':controller(/:action)' 
  match ':controller(/:action(/:id))'
  
  resources :home
 
  resources :admin_panel
  
  
  root :to => "home#index"
  
end

app/models/duel.rb
class Duel < ActiveRecord::Base
  has_many :bets, :dependent => :destroy
 
  
  protected

  # za każdy dobrze postawiony zakład wypłacamy użytkownikowi pieniądze i usuwamy zakład
  def finish_bet
    @bets = self.bets
    if self.finished == true
      @bets.each {|bet| if bet.winner == self.winner then 
        @user = User.find_by_id(bet.user_id)
        @user.gold += 2*bet.gold
        @user.save
      end 
      bet.destroy}
    end
  end
end

app/controllers/duels_controller.rb
class DuelsController < ApplicationController
  before_filter :authenticate_admin!

  layout "admin_panel"
  
  def index
    @duels = Duel.order("date ASC")
  end

  def show
    @duel = Duel.find(params[:id])
  end

  def new
    @duel = Duel.new
  end

  def edit
    @duel = Duel.find(params[:id])
  end

  def create
    @duel = Duel.new(params[:duel])

    if @duel.save
      redirect_to(duels_path, :notice => 'Pojedynk został pomyślnie stworzony.')
    else
      render :action => "new"
    end
  end

  def update
    @duel = Duel.find(params[:id])

    if @duel.update_attributes(params[:duel])
      redirect_to(duels_path, :notice => 'Pojedynek został pomyślnie zaktualizowany.')
    else
      render :action => "edit"
    end
  end

  # strona na której administrator uzupełnia wynik pojedynku
  def result
    @duel = Duel.find(params[:id])
  end
  # akcja aktualizacji pojedynku
  def make_result
    @duel = Duel.find(params[:id])
    if @duel.update_attributes(params[:duel])
      redirect_to(duels_path, :notice => 'Pojedynek został pomyślnie zaktualizowany.')
    else
      render :action => :result 
    end
  end

  def destroy
    @duel = Duel.find(params[:id])
    @duel.destroy
      redirect_to(duels_path)
  end
  
end

app/helpers/duels_helper.rb
module DuelsHelper
end

app/views/duels/_form.html.erb
<%= form_for(@duel) do |f| %>
  <% if @duel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duel.errors.count, "error") %> prohibited this duel from being saved:</h2>

      <ul>
      <% @duel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team1, "Drużyna 1" %><br />
    <%= f.text_field :team1 %>
  </div>
  <div class="field">
    <%= f.label :team2, "Drużyna 2" %><br />
    <%= f.text_field :team2 %>
  </div>
  <div class="field">
    <%= f.label :event, "Wydarzenie" %><br />
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :date, "Data" %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit "Zapisz" %>
  </div>
<% end %>

app/views/duels/edit.html.erb
<h1>Edytuj pojedynek</h1>

<%= render 'form' %>

<%= link_to 'Pokaż', @duel %> |
<%= link_to 'Wróć', duels_path %>

app/views/duels/index.html.erb
<h1>Lista pojedynków</h1>

<p id="notice"><%= notice %></p>

<table cellspacing="5">
  <tr>
    <th>Drużyna 1</th>
    <th>Drużyna 2</th>
    <th>Data</th>
    <th>Zakończony</th>
	<th></th>
	<th></th>
	<th></th>
	<th></th>
	<th></th>
  </tr>

<% @duels.each do |duel| %>
  <tr>
    <td><%= duel.team1 %></td>
    <td><%= duel.team2 %></td>
    <td><%= duel.date %></td>
	<td><%if duel.finished%>Tak<%else%>Nie<%end%></td>
    <td><%= link_to 'Pokaż', duel %></td>
	<td><%= link_to 'Edytuj', edit_duel_path(duel) %></td>
	<td><%= link_to 'Usuń', duel, :confirm => 'Jesteś pewien?', :method => :delete %></td>
	<td><%= link_to 'Lista zakładów', duel_bets_path(duel) %></td>
	<td><%= link_to 'Zakończ pojedynek', :action => :result, :id => duel  %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Nowy pojedynek', new_duel_path%>



app/views/duels/new.html.erb
<h1>Nowy pojedynek</h1>

<%= render 'form' %>

<%= link_to 'Wróć', duels_path %>

app/views/duels/result.html.erb
<h1>Wynik pojedynku</h1>

<%= form_for(@duel) do |f| %>
  <% if @duel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duel.errors.count, "error") %> prohibited this duel from being saved:</h2>

      <ul>
      <% @duel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%=@duel.team1%> vs <%=@duel.team2%></p>
  <p>Data: <%=@duel.date%></p>
   <div class="field">
    <%= f.label :winner, "Zwycięzca" %><br>
    <%= f.select :winner, [["Brak", ""],[@duel.team1, @duel.team1], [@duel.team2, @duel.team2]], :required => true %><br>
  </div>
  <div class="field">
  <%= f.radio_button :finished, true %>Zakończono<br>
  <%= f.radio_button :finished, false %>Nie zakończono<br>
  </div>
  <div class="actions">
    <%= f.submit "Zakończ pojedynek", :action => :make_duel_result%>
  </div>
<% end %>

<%= link_to 'Wróć', duels_path %>

app/views/duels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Drużyna 1:</b>
  <%= @duel.team1 %>
</p>

<p>
  <b>Drużyna 2:</b>
  <%= @duel.team2 %>
</p>

<p>
  <b>Data:</b>
  <%= @duel.date %>
</p>

<p>
  <b>Wydarzenie:</b>
  <%= @duel.event %>
</p>

<%= link_to 'Edytuj', edit_duel_path(@duel) %> |
<%= link_to 'Wróć', duels_path %>