config/routes.rb
Sc2tvZaklady::Application.routes.draw do

  resources :suggestions

  devise_for :admins
  devise_for :users
  
  resources :posts do
    resources :comments
  end
  
  resources :duels do
    member do
      get :result
      put :make_result
    end
    resources :bets
  end

  resources :users do
    resources :bets
  end

  resources :suggestions

  match ':controller(/:action)' 
  match ':controller(/:action(/:id))'
  
  resources :home
 
  resources :admin_panel
  
  
  root :to => "home#index"
  
end

app/models/bet.rb
class Bet < ActiveRecord::Base
belongs_to :duel
belongs_to :user
before_destroy :refund_gold
validate :duel_can_not_be_started
validates_numericality_of :gold, :only_integer => true

protected
 # zwaramy pieniądze użytkownikowi jesli pojedynek się jeszcze nie rozpoczął
 def refund_gold
   @duel = Duel.find_by_id(self.duel_id)
   if @duel.date > Time.now then
    @user = User.find_by_id(self.user_id)
    @user.gold += self.gold
    @user.save
   end
 end
  # czas i data rozpoczęcia pojedynku musi być późniejsza niż aktualna
 def duel_can_not_be_started
    errors.add :duel if duel.date < Time.now.utc
 end
 
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

  before_filter :find_duel, :find_user
  
  before_filter :auth_admin_owner, :except => [:new, :create, :index]
  
  before_filter :authenticate_user!, :only => [:new, :create]

  before_filter :check_date, :except => [:index, :show]

  
   def index
      if @user
        @bets = @user.bets
      else
        @bets = @duel.bets
        render :action => "index", :layout => "admin_panel"
      end
   end

  def new
    @user = current_user
    @bet = @duel.bets.build
  end
  
  def create
    @user = current_user
    @bet = @duel.bets.build(params[:bet])

    if @bet.save     
      @user.gold -= @bet.gold
      @user.save
      redirect_to({:controller => :home, :action => :show_duel, :id => @duel},  :notice => 'Nowy zaklad potwierdzony')
    else
      render :action => "new"
    end
    
  end
  
  def edit
    @bet = Bet.find(params[:id])
  end
  
  def show
    @bet = Bet.find(params[:id])
  end
  
  def update
    @bet = Bet.find(params[:id])
    @bet.update_attributes(params[:bet])
    redirect_to duel_bets_path(@duel)
  end
  
  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy 
    if @user
      redirect_to user_bets_path(@user)
    else
      redirect_to duel_bets_path(@duel)
    end
  end
  
protected
  # sprawdzanie czy jesteśmy zalogowaniu jako użytkownik lub administrator
  def auth_admin_owner
    @bet = Bet.find(params[:id])
    if !(@bet.user_id == current_user.id || :authenticate_admin!)
      redirect_to new_user_session_path
    end
  end
  # sprawdzanie czy pojedynek się jeszcze nie rozpoczął
  def check_date
    @duel = Duel.find(params[:duel_id])
    if @duel.date < Time.now then
      redirect_to :controller => :home, :action => :duels
    end
  end
  # jeśli parametrem jest duel_id to wyszukujemy pojedynek
  def find_duel
    @duel = Duel.find(params[:duel_id]) if params[:duel_id]
  end
 # jeśli parametrem jest user_id to wyszukujemy użytkownika
  def find_user
     @user = User.find(params[:user_id]) if params[:user_id]
 end

end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for([@duel, @bet]) do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2>Poniższy/e błąd/błędy nie pozwoliły na postawienie zakładu:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :winner, "Zwycięzca" %><br />
	<%= f.select :winner, [[@duel.team1, @duel.team1], [@duel.team2, @duel.team2]], :required => true %>
  </div>
  <div class="field">
    <%= f.label :gold , "Kasa"%><br />
    <%= f.text_field :gold %>
  </div>
  <%= hidden_field(:bet, :user_id, :value => @user.id) %>
  <div class="actions">
    <%= f.submit "Utwórz" %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Edycja zakładu</h1>

<%= render 'form' %>

<%= link_to 'Show', duel_bet_path(@duel, @bet) %> |
<%= link_to 'Back', duel_bets_path(@duel) %>

app/views/bets/index.html.erb
<% if @duel %>
<h1>Lista zakładów pojedynku: <%= @duel.team1%> vs <%= @duel.team2%></h1>

<table>
  <tr>
  	<th>Zwycięzca</th>
    <th>Kasa</th>
	<th>Użytkownik</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bets.each do |bet| %>
  <tr>
  	<td><%= bet.winner %></td>
    <td><%= bet.gold %></td>
	<td><%= bet.user.email %></td>
    <td><%= link_to 'Pokaż', duel_bet_path(@duel, bet) %></td>
    <td><%= link_to 'Edytuj', edit_duel_bet_path(@duel, bet) %></td>
    <td><%= link_to 'Usuń', duel_bet_path(@duel, bet), :confirm => 'Jesteś pewien?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%if @duel.date > Time.now%>
<%= link_to 'Nowy zakład', new_duel_bet_path %><br>
<%end%>
<%= link_to 'Wróć', duels_path %>

<%end%>


<% if @user %>
<div id="middle_cont">
<h2>Lista twoich zakładów</h2>

<table border="2" cellpadding="2" cellspacing="0">
  <tr>
  	<th>Pojedynek</th> 
  	<th>Twój typ</th> 
	<th>Kiedy</th> 
    <th>Kasa</th>
    <th></th>
  </tr>

<% @bets.each do |bet| %>
  <tr>
  	<td><%= bet.duel.team1%> vs <%= bet.duel.team2%></td>
  	<td><%= bet.winner %></td>
	<td><%= bet.duel.date %></td>
    <td><%= bet.gold %></td>
    <td><%= link_to 'Usuń', user_bet_path(@user, bet), :confirm => 'Jesteś pewien?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Wróć', :controller => :home, :action => :user_acc %>

<%end%>
</div>

app/views/bets/new.html.erb
<div id="middle_cont">
<h1>Nowy zakład</h1>

<%= render 'form' %>

<%= link_to 'Wróć', :controller => :home, :action => :show_duel, :id => @duel%>
</div>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>