config/routes.rb
Sc2tvZaklady::Application.routes.draw do

  resources :suggestions

  devise_for :admins
  devise_for :users
  
  resources :posts do
    resources :comments
  end
  
  resources :duels do
    member do
      get :result
      put :make_result
    end
    resources :bets
  end

  resources :users do
    resources :bets
  end

  resources :suggestions

  match ':controller(/:action)' 
  match ':controller(/:action(/:id))'
  
  resources :home
 
  resources :admin_panel
  
  
  root :to => "home#index"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # strona główna
  def index
    @posts = Post.all.reverse
    @posts = @posts.paginate(:page => params[:page], :per_page => 8)
  end

  # strona z konkretnym newsem
  def show_news
    @user = current_user
    @post = Post.find(params[:id])
    @comments = @post.comments.reverse.paginate(:page => params[:page], :per_page => 5)
    @comment = @post.comments.build
  end

  # strona z nie zakończonymi pojedynkami
  def duels
    @duels = Duel.where(:finished => false).order("date ASC").paginate(:page => params[:page], :per_page => 5)
  end

  # archiwum pojedynkow
  def arch_duels
    @duels = Duel.where(:finished => true).order("date ASC").reverse.paginate(:page => params[:page], :per_page => 5)
  end

  # konkretny pojedynek
  def show_duel
    @duel = Duel.find(params[:id])
    @time = Time.now.utc
  end

  # konto użytkownika
  def user_acc
    @user = current_user
  end

  # ranking graczy
  def ranking
    @users = User.order("gold ASC").reverse
  end
  
end

app/helpers/home_helper.rb
module HomeHelper  
end

app/views/home/arch_duels.html.erb
<div id="site_title">Zakończone pojedynki</div>
<div id="middle_cont">
<table cellpadding="2" cellspacing="0" border="2" align="center">
	<tr class="title-duel-line">
		<th>Drużyna 1</th>
		<th>Drużyna 2</th>
	    <th>Status</th>
        <th>Data</th>
		<th></th>
	</tr>
	<% @duels.each do |duel|%>
	<tr class="duel-line">
		<td><%= duel.team1%></td>
		<td><%= duel.team2%></td>
        <td>Zakończony</td>
		<td><%= duel.date%></td>
		<td><%= link_to 'Szczegóły' , :controller => :home, :action => :show_duel, :id => duel %></td>
	</tr>
	<%end%>
</table><br><br>
 <%= will_paginate @duels%>
</div>

app/views/home/duels.html.erb
<div id="site_title">Nadchodzące pojedynki</div>
<div id="middle_cont">
<table cellpadding="2" cellspacing="0" border="2" align="center">
	<tr class="title-duel-line">
		<th>Drużyna 1</th>
		<th>Drużyna 2</th>
	    <th>Status</th>
        <th>Data</th>
		<th></th>
	</tr>
	<% @duels.each do |duel|%>
	<tr class="<% if duel.date > Time.now%>duel-line<%else%>duel-line<%end%>">
		<td><%= duel.team1%></td>
		<td><%= duel.team2%></td>
	    <td><%if duel.date < Time.now %>Rozpoczęty<%else%>Nierozpoczęty<%end%></td>
        <td><%= duel.date%></td>
		<td><%= link_to 'Szczegóły' , :controller => :home, :action => :show_duel, :id => duel %></td>
	</tr>
	<%end%>
</table><br><br>
<%= will_paginate @duels%>
</div>

app/views/home/index.html.erb
<div id="middle_cont">
<div id="site_title">Newsy</div>
<% @posts.each do |post| %>
<div class="news">
	<div class="news_title">
		<%= post.title %>
	</div>
	<div class="news_desc">
		<%= raw(post.short_desc) %>
        <%= link_to "Czytaj więcej... (#{post.comments.count})", :controller => :home, :action => :show_news, :id => post %>
        <div class="news_added_time"> Dodano: <%=post.created_at%> </div>
    </div>
	<hr>
</div>
<%end%>
<%= will_paginate @posts%> 
</div>

app/views/home/ranking.html.erb
<div id="site_title">Ranking graczy</div>
<div id="middle_cont">
	<table cellpadding="2" cellspacing="0" border="1" align="center">
		<tr>
			<th>Miejsce</th>
			<th>Użytkownik</th>
			<th>Kasa</th>
		</tr>
		<%for i in 1..@users.count%>
		<tr class="<%= cycle('ranking-line-odd', 'ranking-line-even') %>">
			<td><%=i%></td>
			<td><%=@users[i-1].username%></td>
			<td><%=@users[i-1].gold%></td>
		</tr>
		<%end%>
	</table>
</div>

app/views/home/show_duel.html.erb
<div id="site_title">Pojedynek: <%=@duel.team1%> vs <%=@duel.team2%></div>
<div id="middle_cont">
	<p>Kiedy start: <%=@duel.date%></p>
	<p>Wydarzenie: <%=@duel.event%></p>
	<p>Status: 
	<%if @duel.finished%>Zakończony<%elsif @duel.date < @time%>Rozpoczęty<%else%>Nierozpoczęty<%end%></p>
	<p>Ilość zakładów: <%=@duel.bets.count%></p>
	<% if @duel.finished%><p>Zwycięzca: <%=@duel.winner%></p><%end%>
	<%if (@duel.date > Time.now) && !@duel.finished%>
		<%= link_to 'Postaw zakład', new_duel_bet_path(@duel)%><br>
	<%end%>
    <% if !@duel.finished %>
	    <%= link_to 'Wróć', :action => :duels %>
    <%else%>
        <%= link_to 'Wróć', :action => :arch_duels %>
    <%end%>
</div>

app/views/home/show_news.html.erb
<div id="show_news">
	<span class="news_title">
		<%= @post.title %>
	</span>
	<span class="news_desc">
		<%= raw(@post.description) %>
	</span>
	<hr>
	<p id="comments_title">Komentarze:</p>
		<% @comments.each do |comment| %>
		<%if !comment.id.blank?%>
			<div class="comment">
				<span class="comment_body">
					<%= comment.content %>
					<%if ((@user && (@user.id == comment.user_id))) || admin_signed_in? %>
                        <%= link_to 'Edytuj', :controller => :comments, :action => :edit, :post_id => @post, :id => comment  %>
						<%= link_to 'Usuń', :controller => :comments, :action => :destroy, :id => @post, :comment_id => comment  %>
					<%end%>
				</span>
				<span class="comment_date">
					<%= comment.user.username%><br>
					<%= comment.created_at %>
				</span>
				<hr class="comment_under_line" color="#f67326" size="1">
			</div>
		<%elsif @comments.count == 0%>
			<span class="comment">
				Brak komentarzy.
			</span>
		<%end%>
		<%end%>
  <%= will_paginate @comments%>
		
	<div id="comment_form">
	<%if @user%>
	<%= form_for([@post, @comment]) do |f| %>
  		<div class="field">
    		<%= f.label :content, "Tekst" %><br />
			<%= f.text_area :content, :cols => 70, :rows => 4%>
  		</div>
		<%= f.hidden_field(:user_id, :value => @user.id) %>
  		<div class="actions">
    		<%= f.submit "Dodaj komentarz" %>
  		</div>
	<%end%>
	<%else%>
	    <%= link_to "Zaloguj się aby dodać komentarz.", new_user_session_path%><br>
    <%end%>
    <%= link_to 'Wróć', :action => :index%>
	</div>
</div>

app/views/home/user_acc.html.erb
<div id="middle_cont">
<h2>Twoje konto</h2>
Nazwa użytkownika: <%= @user.username %><br>
E-mail: <%= @user.email %><br>
Kasa: <%= @user.gold %>
<br><br>

<%= link_to "Twoje zakłady", user_bets_path(@user) %>  
</div>