config/routes.rb
Sc2tvZaklady::Application.routes.draw do

  resources :suggestions

  devise_for :admins
  devise_for :users
  
  resources :posts do
    resources :comments
  end
  
  resources :duels do
    member do
      get :result
      put :make_result
    end
    resources :bets
  end

  resources :users do
    resources :bets
  end

  resources :suggestions

  match ':controller(/:action)' 
  match ':controller(/:action(/:id))'
  
  resources :home
 
  resources :admin_panel
  
  
  root :to => "home#index"
  
end

app/views/layouts/admin_panel.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sc2tvZaklady</title>
  <%= stylesheet_link_tag  'scaffold', 'admin_panel' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= include_tiny_mce_if_needed %>
</head>
<body>
<div id="admin_top">
	<p id="top_title">Panel administracyjny</p>
    <p id="admin_logout" >Zalogowany jako: <%= current_admin.username %>, <%= link_to "Wyloguj",  destroy_admin_session_path(current_admin) %></p>
</div>
<div id="top_menu">
	<%=link_to 'Newsy', posts_path %>
	<%=link_to 'Pojedynki', duels_path %>
	<%=link_to 'Użytkownicy', users_path %>
    <%=link_to 'Propozycje pojedynków', suggestions_path %>
</div>
<div id="container">
	<%= yield%>
</div>
<div id="admin_footer"></div>
</body>
</html>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sc2tvZaklady</title>
  <%= stylesheet_link_tag 'scaffold', 'sc2tv' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="header1"></div>
<table id="main_table" cellpadding="0" cellspacing="0" >
	<tr>
	<td id="container">
		
	<div id="top_menu">
		<%= link_to 'Strona główna', home_index_path %> | 
		<%= link_to 'Lista pojedynków',:controller => :home, :action => :duels %> |
		<%= link_to 'Archiwum pojedynków',:controller => :home, :action => :arch_duels %> |
		<%= link_to 'Ranking graczy',:controller => :home, :action => :ranking %> |
		<%= link_to 'Zaproponuj pojedynek', new_suggestion_path %>
        <%if !user_signed_in? %>
			| <%= link_to 'Logowanie', new_user_session_path %> | 
			<%= link_to 'Rejestracja', new_user_registration_path %>
		<%end%>
	</div>
	<div class="side">
		<img src="/images/left_top.jpg"></img>
		
		<div class="modul_title">Facebook</div>
		<div class="modul_container">
			Znajdz nas na facebook'u
		</div>
		
		<img src="/images/left_bottom.jpg"></img>
	</div>

	<div id="middle">
    <p id="notify"><%= notice %></p>

		<%=yield %>
	</div>

	<div class="side">
		<img src="/images/right_top.jpg"></img>
		<%= render :partial => "home/partials/user_acc" %>
		<img src="/images/right_bottom.jpg"></img>
	</div>
	</td>
	</tr>
	
</table>



<div id="footer">
	Zakłady SC2tv.pl 2010. All rights reserved 
</div>
</body>


</html>